provider: local
replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "latest"

auth:
  rootUsername: admin
  rootPassword: admin
  username: example
  password: example
  database: example

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

service:
  type: ClusterIP
  port: 27017

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

persistence:
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  hostPath: /tmp/nosql
