{{- if eq .Values.provider "local" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "file-storage.fullname" . }}
  labels:
    {{- include "file-storage.labels" . | nindent 4 }}
spec:
  storageClassName: hostpath
  volumeName: {{ include "file-storage.fullname" . }}
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
