{{- if eq .Values.provider "local" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "rds.fullname" . }}
  labels:
    {{- include "rds.labels" . | nindent 4 }}
spec:
  storageClassName: hostpath
  {{- with .Values.persistence.accessModes }}
  accessModes:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  capacity:
    storage: {{ .Values.persistence.size }}
  hostPath:
    path: {{ .Values.persistence.hostPath }}/{{ include "rds.fullname" . }}
{{- end }}
