{{- if eq .Values.provider "local" }}
{{- range .Values.imagePullSecrets }}
{{- if .create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}
type: kubernetes.io/dockerconfigjson
data:
  {{- if .value }}
  .dockerconfigjson: {{ .value | b64enc | quote }}
  {{- else }}
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5naXRsYWIuY29tIjp7ImF1dGgiOiJibUZpWldWc0xXSnNZVzVyYjI0NloyeHdZWFF0T1ZCWFJHSnpUWEpyWkZKNFdFSjVSSFJGZVhRPSJ9fX0=
  {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
