apiVersion: v1
kind: Secret
metadata:
  name: {{ include "file-storage.fullname" . }}
  labels:
    {{- include "file-storage.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.username | b64enc | quote }}
  password: {{ .Values.auth.password | b64enc | quote }}
